spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sikcal.cjnhnl3rox8c.ap-northeast-2.rds.amazonaws.com:3306/sikcal
    username: admin
    password: sikcal1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  mvc: ##swagger연동을 위한 설정
    pathmatch:
      matching-strategy: ant_path_matcher

##logging:
##  level:
##    org.hibernate.SQL: debug
##server:
##  port= 8090


logging:
  level:
    org.hibernate.SQL: debug
